M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date Sat 13 Apr 2024 14:39:46 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-13T14:39:46+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X66.837Y-110.754
X66.837Y-116.534
T2
X64.27Y-83.52
X64.27Y-91.52
T3
X62.596Y-145.344
X62.67Y-46.91
X195.0Y-46.91
X195.0Y-145.344
T0
M30
