M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date Fri 22 Dec 2023 22:10:07 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-22T22:10:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X45.47Y-51.5
X51.25Y-51.5
T2
X34.6Y-35.15
X60.91Y-54.92
X90.3Y-35.15
T0
M30
